name: Lint & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    uses: igor-siergiej/utils/.github/workflows/lint-test.yml@main
    with:
      package-manager: bun
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
